name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.16
  - pip=23.0.1
  - sphinx
  - sphinx_rtd_theme
  - mdtraj=1.9.7
  - numba=0.57.0
  - numpy=1.24.3
  - openmm=8.0.0
  - scipy=1.9.3
  - setuptools=66.0.0
  - openmmtools=0.22.1
  - pandas=2.0.1
  - matplotlib-base=3.7.1
  - pip:
    - cached-property==1.5.2
    - cachetools==5.3.1
    - cma==3.3.0
    - dill==0.3.6
    - stdio-proxy==0.1.3
    - parmed==4.2.2
  


