name: openmmslicer
channels:
  - conda-forge
  - omnia
dependencies:
  - python
  - setuptools
  - numpy
  - scipy
  - mdtraj
  - pandas
  - numba
  - pip:
      - cached-property
      - cachetools
      - cma
      - dill
      - stdio-proxy

